version: '2.2'

services:
  urzad-visitor:
    image: jctim/urzad-visitor:latest
    build: .
    container_name: urzad-visitor
    hostname: urzad-visitor
    volumes:
      - ./logs:/opt/app/logs
      - ./data:/opt/app/data
    command:
      - python3
      - urzad_visitor.py
